# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

module Pangea
  module Resources
    module Dns
      include DnsARecordSet
      include DnsAaaaRecordSet
      include DnsCnameRecord
      include DnsMxRecordSet
      include DnsNsRecordSet
      include DnsPtrRecord
      include DnsSrvRecordSet
      include DnsTxtRecordSet
    end
  end
end
