# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/dns_srv_record_set/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module DnsSrvRecordSet
    include Pangea::Resources::ResourceBuilder

    define_resource :dns_srv_record_set,
      attributes_class: Dns::Types::SrvRecordSetAttributes,
      outputs: { id: :id },
      map: [:name, :zone],
      map_present: [:srv]
  end
  module Dns
    include DnsSrvRecordSet
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Dns)
