# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Dns::Types
  include Dry.Types()

  class SrvRecordSetAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Dns::Types

    attribute :name, T::String
    attribute :zone, T::String
    attribute? :srv, T::Array.of(T::Hash).optional
  end
end
