# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/dns_aaaa_record_set/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module DnsAaaaRecordSet
    include Pangea::Resources::ResourceBuilder

    define_resource :dns_aaaa_record_set,
      attributes_class: Dns::Types::AaaaRecordSetAttributes,
      outputs: { id: :id },
      map: [:addresses, :zone],
      map_present: [:name, :ttl]
  end
  module Dns
    include DnsAaaaRecordSet
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Dns)
