# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea-core'
require 'terraform-synthesizer'

module Pangea; module Resources; module Dns; module Types; end; end; end; end

# Dns resources
require_relative 'pangea/resources/dns_a_record_set/resource'
require_relative 'pangea/resources/dns_aaaa_record_set/resource'
require_relative 'pangea/resources/dns_cname_record/resource'
require_relative 'pangea/resources/dns_mx_record_set/resource'
require_relative 'pangea/resources/dns_ns_record_set/resource'
require_relative 'pangea/resources/dns_ptr_record/resource'
require_relative 'pangea/resources/dns_srv_record_set/resource'
require_relative 'pangea/resources/dns_txt_record_set/resource'

# Dns module aggregator
require_relative 'pangea/resources/dns'
