# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/dns_a_record_set/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module DnsARecordSet
    include Pangea::Resources::ResourceBuilder

    define_resource :dns_a_record_set,
      attributes_class: Dns::Types::ARecordSetAttributes,
      outputs: { id: :id },
      map: [:addresses, :zone],
      map_present: [:name, :ttl]
  end
  module Dns
    include DnsARecordSet
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Dns)
