# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/dns_ns_record_set/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module DnsNsRecordSet
    include Pangea::Resources::ResourceBuilder

    define_resource :dns_ns_record_set,
      attributes_class: Dns::Types::NsRecordSetAttributes,
      outputs: { id: :id },
      map: [:name, :nameservers, :zone]
  end
  module Dns
    include DnsNsRecordSet
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Dns)
