# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Dns::Types
  include Dry.Types()

  class NsRecordSetAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Dns::Types

    attribute :name, T::String
    attribute :nameservers, T::Array.of(T::String)
    attribute :zone, T::String
  end
end
