# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/dns_ptr_record/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module DnsPtrRecord
    include Pangea::Resources::ResourceBuilder

    define_resource :dns_ptr_record,
      attributes_class: Dns::Types::PtrRecordAttributes,
      outputs: { id: :id },
      map: [:ptr, :zone],
      map_present: [:name]
  end
  module Dns
    include DnsPtrRecord
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Dns)
