# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Dns::Types
  include Dry.Types()

  class PtrRecordAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Dns::Types

    attribute :ptr, T::String
    attribute :zone, T::String
    attribute? :name, T::String.optional
  end
end
