# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/dns_cname_record/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module DnsCnameRecord
    include Pangea::Resources::ResourceBuilder

    define_resource :dns_cname_record,
      attributes_class: Dns::Types::CnameRecordAttributes,
      outputs: { id: :id },
      map: [:cname, :name, :zone]
  end
  module Dns
    include DnsCnameRecord
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Dns)
