# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Dns::Types
  include Dry.Types()

  class CnameRecordAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Dns::Types

    attribute :cname, T::String
    attribute :name, T::String
    attribute :zone, T::String
  end
end
