# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/dns_mx_record_set/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module DnsMxRecordSet
    include Pangea::Resources::ResourceBuilder

    define_resource :dns_mx_record_set,
      attributes_class: Dns::Types::MxRecordSetAttributes,
      outputs: { id: :id },
      map: [:zone],
      map_present: [:mx, :name]
  end
  module Dns
    include DnsMxRecordSet
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Dns)
