# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a dns_ptr_record resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::DnsPtrRecord do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { ptr: 'test-value', zone: 'test-value' } }

  describe ':dns_ptr_record' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.dns_ptr_record('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'dns_ptr_record', 'test')
        validate_required_attributes(config, [:ptr, :zone])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.dns_ptr_record('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:dns_ptr_record)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.dns_ptr_record('test', required_attrs)

        expect(ref.id).to eq("${dns_ptr_record.test.id}")
        expect(ref.ttl).to eq("${dns_ptr_record.test.ttl}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.dns_ptr_record('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'dns_ptr_record', 'test')
        expect(config).not_to have_key('ttl')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ name: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.dns_ptr_record('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'dns_ptr_record', 'full')
        expect(config).to have_key('name')
      end
    end

    context 'optional attributes' do
      it 'includes name when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.dns_ptr_record('opt', required_attrs.merge(name: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'dns_ptr_record', 'opt')
        expect(config).to have_key('name')
      end

      it 'omits name when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.dns_ptr_record('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'dns_ptr_record', 'minimal')
        expect(config).not_to have_key('name')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.dns_ptr_record('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'dns_ptr_record', 'typed')
        expect(config['ptr']).to be_a(String)
        expect(config['zone']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.dns_ptr_record('first', required_attrs)
        synth.dns_ptr_record('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'dns_ptr_record')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :dns_ptr_record,
    method: :dns_ptr_record,
    required_attrs: { ptr: 'test-value', zone: 'test-value' },
    expected_outputs: [:id, :ttl],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
